// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDu64SmJEK3n2N_i0f9WPDGsiPnnBuqWCk',
    appId: '1:814772031148:web:2558279dc9d26083da9909',
    messagingSenderId: '814772031148',
    projectId: 'ayubolife-23d00',
    authDomain: 'ayubolife-23d00.firebaseapp.com',
    storageBucket: 'ayubolife-23d00.firebasestorage.app',
    measurementId: 'G-MDV9TBBLT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZfWXV0tBBJ2oAMkoRZ_dNuwLnWMEI2t0',
    appId: '1:814772031148:android:be15e2ad41b873e7da9909',
    messagingSenderId: '814772031148',
    projectId: 'ayubolife-23d00',
    storageBucket: 'ayubolife-23d00.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ_aeNhyc7XK99HPE6LFolglMlqA56WQI',
    appId: '1:814772031148:ios:6f1090c146941e71da9909',
    messagingSenderId: '814772031148',
    projectId: 'ayubolife-23d00',
    storageBucket: 'ayubolife-23d00.firebasestorage.app',
    androidClientId: '814772031148-sibvl0ksabv3418k1cgn191d5lmqq9fh.apps.googleusercontent.com',
    iosClientId: '814772031148-l1mqq283e7s9g86mgjvi77fseukljk1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayubolife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ_aeNhyc7XK99HPE6LFolglMlqA56WQI',
    appId: '1:814772031148:ios:6f1090c146941e71da9909',
    messagingSenderId: '814772031148',
    projectId: 'ayubolife-23d00',
    storageBucket: 'ayubolife-23d00.firebasestorage.app',
    androidClientId: '814772031148-sibvl0ksabv3418k1cgn191d5lmqq9fh.apps.googleusercontent.com',
    iosClientId: '814772031148-l1mqq283e7s9g86mgjvi77fseukljk1o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ayubolife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDu64SmJEK3n2N_i0f9WPDGsiPnnBuqWCk',
    appId: '1:814772031148:web:0f07af696d54ddbcda9909',
    messagingSenderId: '814772031148',
    projectId: 'ayubolife-23d00',
    authDomain: 'ayubolife-23d00.firebaseapp.com',
    storageBucket: 'ayubolife-23d00.firebasestorage.app',
    measurementId: 'G-Q0BWEBC7M4',
  );
}
